require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '14.4.2'
install! 'cocoapods', :deterministic_uuids => false

target 'spenowr' do
  config = use_native_modules!
  # pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  # pod ‘RNFBAdMob’, :path => ‘../node_modules/@react-native-firebase/admob’
  # pod 'Google-Mobile-Ads-SDK', '~> 11.5.0'
  use_react_native!( 
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )
  # $RNFirebaseAnalyticsWithoutAdIdSupport=true

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({'Flipper' => '0.110.0' , 'Flipper-Folly' => '2.6.9' , 'Flipper-RSocket' => '1.4.3' })
  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end